version: '3'

services:

  database:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_DATABASE: gitlabrs
      MYSQL_USER: gitlabrs_user
      MYSQL_PASSWORD: gitlabrs_password
      MYSQL_ROOT_PASSWORD: gitlabrs_root_password

  api:
    build: ./api
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./api/app:/app
    env_file:
      - .env
    environment: 
      GITLAB_ENDPOINT: ${GITLAB_ENDPOINT}
      GITLAB_ACCESS_TOKEN: ${GITLAB_ACCESS_TOKEN}